spring.application.name=bookstore_Eshopping_web

server.port=9091

spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_eshopping
spring.datasource.username=root



spring.datasource.password=Rama#@1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


spring.security.user.name=user
spring.security.user.password=1234

logging.file.name=myapp.log #  Name of the log file
spring.output.ansi.enabled=always
logging.level.root=INFO
logging.level.com.hcl=DEBUG
logging.file.path=./logs

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

