package com.hcl.entity;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class BookTest {

    @Test
    void testNoArgsConstructor() {
        Book book = new Book();
        assertNull(book.getBookId());
        assertNull(book.getBookName());
        assertNull(book.getAuthorName());
        assertNull(book.getQuantity());
        assertNull(book.getPrice());
    }

    @Test
    void testAllArgsConstructor() {
        Book book = new Book("The Lord of the Rings", "J.R.R. Tolkien", 10, 25.99);
        assertNull(book.getBookId()); // ID is generated by the database
        assertEquals("The Lord of the Rings", book.getBookName());
        assertEquals("J.R.R. Tolkien", book.getAuthorName());
        assertEquals(10, book.getQuantity());
        assertEquals(25.99, book.getPrice(), 0.001); // Use delta for double comparison
    }

    @Test
    void testGettersAndSetters() {
        Book book = new Book();
        book.setBookId(1L);
        book.setBookName("Pride and Prejudice");
        book.setAuthorName("Jane Austen");
        book.setQuantity(5);
        book.setPrice(12.50);

        assertEquals(1L, book.getBookId());
        assertEquals("Pride and Prejudice", book.getBookName());
        assertEquals("Jane Austen", book.getAuthorName());
        assertEquals(5, book.getQuantity());
        assertEquals(12.50, book.getPrice(), 0.001);
    }
}